# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Chimp
version:      0.1
version_from: lib/Mail/Chimp.pm
installdirs:  site
requires:
    Mouse:                         0.16
    Test::Simple:                  0.44
    XMLRPC::Lite:                  0.710.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
